apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-commerce-app
spec:
  replicas: 2
  selector:
    matchLables:
      app: e-commerce-app
  template: 
    metadata:
      labels:
        app:e-commerce-app
